FROM tomcat:9.0.76

RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN rm -rf /usr/local/tomcat/webapps/ROOT/*
COPY cluster.tar /usr/local/tomcat/webapps/ROOT/cluster.tar
COPY context.xml /usr/local/tomcat/conf/context.xml
COPY dbtest.jsp /usr/local/tomcat/webapps/ROOT/dbtest.jsp
COPY mysql-connector-j-8.0.33.jar /usr/local/tomcat/lib/mysql-connector-j-8.0.33.jar
RUN tar -xf /usr/local/tomcat/webapps/ROOT/cluster.tar -C /usr/local/tomcat/webapps/ROOT


EXPOSE 8080
CMD ["catalina.sh", "run"]
