FROM nginx:1.15

RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN rm -rf /usr/share/nginx/html/*
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx.tar /usr/share/nginx/html/nginx.tar
RUN tar -xf /usr/share/nginx/html/nginx.tar -C /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]